name: build and publish
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to gchr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Istall linuxkit
        run: curl -L -o /usr/bin/linuxkit https://github.com/linuxkit/linuxkit/releases/download/v0.8/linuxkit-linux-amd64 && chmod +x /usr/bin/linuxkit
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build LinuxKit
        run: linuxkit build -format iso-efi dind.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dind-*
 

