name: build and publish
on: [push]
jobs:
  push_to_registry:
    name: build linuxkit image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install linuxkit
        run: mkdir -p build && curl -L -o build/linuxkit https://github.com/jclab-joseph/linuxkit/releases/download/v0.9jclab-rc01/linuxkit-amd64-linux && chmod +x build/linuxkit
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build LinuxKit
        run: PATH="$PWD/build:$PATH" ./build-image.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/dind-*

